singleQuote: true
trailingComma: all
tabWidth: 2
endOfLine: lf
printWidth: 120
overrides:
  - files:
      - '*.js'
      - '*.ts'
      - '*.jsx'
      - '*.tsx'
    options:
      tabWidth: 4
  - files: '*.vue'
    options:
      tabWidth: 4
      printWidth: 160
